version: "3"
services:
  # PostgreSQL Database for the application
  PostgreSQL:
    image: postgres:14-alpine3.15
    container_name: postgres-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DATABASE_HOST=127.0.0.1
      - APP_DB_USER=postgres
      - APP_DB_PASS=postgres
      - APP_DB_NAME=test_db
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  # Redis memory cache for the application
  redis-cache:
    image: redis:alpine3.15
    container_name: redis-cache-db
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass renos1987
  # Back-end Spring Boot Application
  springboot-docker-container:
    image: springboot-docker-container
    container_name: springboot-docker-container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - PostgreSQL
      - redis-cache
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD-SHELL"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - DB_SERVER=PostgreSQL
      - POSTGRES_DB=test_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/test_db?autoReconnect=true&useSSL=false
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - REDIS_HOST= redis-cache
      - REDIS_PORT= 6379
      - REDIS_PASSWORD= renos1987
    links:
      - PostgreSQL
      - redis-cache
  # This part for restarting the unhealthy container
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
